# Generated by Django 5.0.2 on 2024-03-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/product/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
